linters:
  disable-all: true
  enable:
    - asciicheck
    - decorder
    - dupword
    - durationcheck
    - forcetypeassert
    - godot
    - gofmt
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nilerr
    - nlreturn
    - promlinter
    - reassign
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wsl